version: '3'

rpc:
    listen: 'tcp://127.0.0.1:6001'

http:
    address: '0.0.0.0:8080'
    middleware:
        - gzip
        - static
    static:
        dir: public
        forbid:
            - .php
            - .htaccess
    pool:
        num_workers: 1
        debug: true

server:
    command: 'php app.php'
    relay: pipes

reload:
    interval: 1s
    patterns: [ ".php" ]
    services:
        http:
            recursive: true
            dirs: [ "/data" ]
